# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code_name', models.CharField(max_length=10, verbose_name='Code Name')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['code_name'],
                'verbose_name': 'Country',
            },
        ),
        migrations.DeleteModel(
            name='Telephone',
        ),
    ]
