# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('document_type', models.PositiveSmallIntegerField(choices=[(1, 'DNI')], default=1, verbose_name='Document Type')),
                ('document_number', models.CharField(max_length=255, verbose_name='Document Number')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person')),
                ('speciality', models.CharField(help_text='Medic Speciality', max_length=150, verbose_name='Speciality')),
            ],
            bases=('core.person',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person')),
                ('social_care', models.CharField(blank=True, max_length=150, null=True, verbose_name='Social Care')),
            ],
            bases=('core.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.City'),
        ),
    ]
